src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\ManyToOne(targetEntity: Adminstrateur::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adminstrateur $users = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $prix_unitaire = null;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'produits')]  # Relation ManyToOne
    #[ORM\JoinColumn(nullable: false)]  # Clé étrangère obligatoire
    private ?Categorie $categorie = null;


    #[ORM\Column(type: 'string', length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 500)]
    private ?string $labelle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getUsers(): ?Adminstrateur
    {
        return $this->users;
    }

    public function setUsers(?Adminstrateur $users): static
    {
        $this->users = $users;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getPrixUnitaire(): ?string
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(string $prix_unitaire): static
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(Categorie $categorie): void
    {
        $this->categorie = $categorie;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getLabelle(): ?string
    {
        return $this->labelle;
    }

    public function setLabelle(?string $Labelle): static
    {
        $this->labelle = $Labelle;
        return $this;
    }

}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\Categorie;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Product name :',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'name',
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
                'constraints' => [
                    new Assert\NotBlank(['message' => 'The name cant\'n be null.']),
                ],
            ])
            ->add('quantite', IntegerType::class, [
                'label' => 'Product quantity :',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'quantity',
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
                'constraints' => [
                    new Assert\NotBlank(['message' => 'The quantity must be full.']),
                ],
            ])
            ->add('date', DateType::class, [
                'label' => 'Date :',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'quantity',
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
                'widget' => 'single_text',
                'constraints' => [
                    new Assert\NotBlank(['message' => 'Fill the date please.']),
                ],
            ])
            ->add('prix_unitaire', NumberType::class, [
                'label' => 'Product cost :',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'cost',
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
                'constraints' => [
                    new Assert\NotBlank(['message' => 'The cost must be  under 5 digits and 2 .']),
                ],
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'nom',
                'placeholder' => 'Choose a category',
                'attr' => [
                    'class' => 'form-control',
                ],
                'constraints' => [
                    new Assert\NotBlank(['message' => 'Please choose a category.']),
                ],
            ])
            ->add('image', FileType::class, [
                'label' => 'Upload photo',
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('labelle', TextareaType::class, [
                'label' => 'Enter the description of the article',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Enter the description',
                ],
            ]);
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Adminstrateur;
use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Imagine\Gd\Imagine;
use Imagine\Image\Box;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produit();
        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour créer un produit.');
        }
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $produit->setUsers($user);
            $image = $form->get('image')->getData();
            $description = $form->get('labelle')->getData();
            if ($image) {
                $newFilename = uniqid() . '.' . $image->guessExtension();
                try {
                    $image->move(
                        $this->getParameter('images_directory'),  // Emplacement de stockage
                        $newFilename
                    );

                    // Redimensionner l'image
                    $imagine = new Imagine();
                    $size = new Box(800, 800);  // Taille maximale
                    $imagine->open($this->getParameter('images_directory') . '/' . $newFilename)
                        ->thumbnail($size)
                        ->save();

                    $produit->setImage($newFilename);  // Stocker le nom du fichier d'image dans l'entité
                } catch (FileException $e) {
                    throw new \Exception("Erreur lors du téléchargement de l'image");
                }
            }
            $produit->setLabelle($description);
            $entityManager->persist($produit);
            $entityManager->flush();
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }
        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/user', name: 'app_produit_user', methods: ['GET'])]
    public function getProductUser(EntityManagerInterface $entityManager): Response{
        $user = $this->getUser();  
        if (!$user) {
            throw $this->createAccessDeniedException("Vous devez être connecté pour accéder à cette page.");
        }
        $users = $entityManager->getRepository(Adminstrateur::class)->findOneBy(['email' => $user->getUserIdentifier()]);
        if (!$users) {
            throw $this->createNotFoundException("Utilisateur non trouvé.");
        }
        $produits = $entityManager->getRepository(Produit::class)->findBy(['users' => $users]);
        return $this->render('produit/user_product.html.twig', [
            'produits' => $produits,
        ]);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/produit/_form.html.twig
<div class="row">
    <div class="col-12">
        <div class="breadcrumbs mb-4"> <a href="#">Product</a>
            <span class="mx-1">/</span>  <a href="{{ path('app_produit_index') }}">Liste</a>
            <span class="mx-1">/</span>  <a href="#!">{{ title|default('New') }}</a>
        </div>
    </div>
    <div class="col-lg-12 mt-4 mt-lg-0">
        <div class="card">
            <div class="card-header">
                {{ texte|default('Add product') }}
            </div>
            <div class="card-body">
                {{ form_start(form) }}
                    <div class="row">
                        <div class="col-md-4">
                            {{ form_row(form.nom) }}
                        </div>
                        <div class="col-md-4">
                            {{ form_row(form.quantite) }}
                        </div>
                        {# <p></p> #}
                        <div class="col-md-4">
                            {{ form_row(form.date) }}
                        </div>
                        <div class="col-md-4">
                            {{ form_row(form.prix_unitaire) }}
                        </div>
                        {# <p></p> #}
                        <div class="col-4">
                            {{ form_row(form.categorie) }}
                        </div>
                        <div class="col-4">
                            {{ form_row(form.image) }}
                        </div>
                        <div class="col-12">
                            {{ form_row(form.labelle) }}
                        </div>
                    </div>
                    <p></p>
                    <button class="btn btn-outline-primary " type="submit">{{ button_label|default('Create new product') }}</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    {% include 'produit/_form.html.twig' with {
        'button_label': 'Update product',
        'texte': 'Edit product',
        'title' : 'Edit product'
    } %}

    <a href="{{ path('app_produit_index') }}" class="btn btn-outline-dark">back to list</a>
    <p></p>
    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit list{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12">
        <div class="breadcrumbs mb-4"> <a href="#">Product</a>
            <span class="mx-1">/</span>  <a href="{{ path('app_produit_index') }}">List</a>
        </div>
    </div>
    {% for produit in produits %}
    
        <div class="col-4">
            <div class="card article-card article-card-sm h-100">
                <div class="card-body">
                    <!-- Afficher l'image du produit -->
                    {% if produit.image %}
                        <img src="{{ asset('upload_image/' ~ produit.image) }}" alt="{{ produit.nom }}" class="card-img-top" style="max-height: 200px; object-fit: cover;">  <!-- Ajuster le style selon les besoins -->
                    {% endif %}
                    <p></p>
                    <ul class="post-meta mb-2 ">
                        <li> 
                            <a href="#!">{{ produit.categorie ? produit.categorie.getNom() }}</a>
                        </li>
                    </ul>
                    <h2 class="card-title pricing-card-title"> 
                        <a href="{{ path('app_produit_show', {'id': produit.id}) }}" class="post-title"> {{ produit.nom }} / {{ produit.prixUnitaire }} Ar </a>
                    </h2>
                    <p class="card-text">{{ produit.labelle }}</p>
                </div>
            </div>
        </div>
    {% else %}
        <div class="col-4">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">No records found</h4>
                </div>
            </div>
    {% endfor %}
</div>
<p></p>
<a href="{{ path('app_produit_new') }}" class="btn btn-outline-success">Create new</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}" class="btn btn-outline-dark">Back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit {{ produit.id }} details{% endblock %}

{% block body %}
    <h1>Produit details</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ produit.date ? produit.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img src="{{ asset('upload_image/' ~ produit.image) }}" alt="{{ produit.nom }}" style="max-height: 200px; object-fit: cover;"></td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.labelle }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ produit.quantite }}</td>
            </tr>
            
            <tr>
                <th>Unite price</th>
                <td>{{ produit.prixUnitaire }} Ar</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produit_index') }}" class="btn btn-outline-dark">Back to list</a>
    {% if app.user and produit.users and app.user.id == produit.users.id %}
    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn btn-outline-success">Edit</a>
    
    <p></p>
    {{ include('produit/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}

templates/produit/user_product.html.twig
{% extends 'base.html.twig' %}

{% block title %}My produit list{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12">
        <div class="breadcrumbs mb-4"> <a href="#">Product</a>
            <span class="mx-1">/</span>  <a href="{{ path('app_produit_index') }}">List</a>
        </div>
    </div>
    <div class="col-12">
        <h1>Your product list</h1>
        <div class="card border-success mb-3">
            <div class="card-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nom</th>
                            <th>Quantite</th>
                            <th>Date</th>
                            <th>Prix_unitaire</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for produit in produits %}
                        <tr>
                            <td>{{ produit.id }}</td>
                            <td>{{ produit.nom }}</td>
                            <td>{{ produit.quantite }}</td>
                            <td>{{ produit.date ? produit.date|date('Y-m-d') : '' }}</td>
                            <td>{{ produit.prixUnitaire }}</td>
                            <td>
                                <a href="{{ path('app_produit_show', {'id': produit.id}) }}" class="btn btn-outline-dark">Show</a>
                                <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn btn-outline-success">Edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
    <a href="{{ path('app_produit_new') }}" class="btn btn-outline-success">Create new</a>
{% endblock %}